on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
jobs:
  ci:
    name: Deploy to supabase
    runs-on: ubuntu-22.04

    steps:
    - uses: supabase/setup-cli@v1
    - run: supabase functions deploy
