on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
jobs:
  ci:
    name: Deploy to supabase
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: supabase/setup-cli@v1
    - run: ls
    - run: supabase link --project-ref $PROJECT_ID
    - run: supabase functions deploy
